services:
  mysql-1:
    image: mysql:5.7
    container_name: mysql-1
    restart: unless-stopped
    ports:
    - 3306:3306
    volumes:
    - ./data/mysql-1:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root1
    command:
    - --server-id=1
    - --log-bin=mysql-bin
    - --binlog-format=ROW
    - --gtid-mode=ON
    - --enforce-gtid-consistency=ON
    - --skip-name-resolve=1
    - --default-authentication-plugin=mysql_native_password
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
      - -h
      - 127.0.0.1
      - -uroot
      - -proot1
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s
  mysql-2:
    image: mysql:8.0
    container_name: mysql-2
    restart: unless-stopped
    ports:
    - 3307:3306
    volumes:
    - ./data/mysql-2:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root2
    command:
    - --server-id=1
    - --log-bin=mysql-bin
    - --binlog-format=ROW
    - --gtid-mode=ON
    - --enforce-gtid-consistency=ON
    - --skip-name-resolve=1
    healthcheck:
      test:
      - CMD
      - mysqladmin
      - ping
      - -h
      - 127.0.0.1
      - -uroot
      - -proot2
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 20s
